#!/bin/bash

echo -e "\n+++ GITVERS-TOOL INSTALLATION +++"

# download gitvers-tool from repository
sleep 1
sudo curl https://raw.githubusercontent.com/RajaRakoto/gitvers-tool/master/gitvers-tool > /usr/local/bin/gitvers-tool
sudo chmod a+rx /usr/local/bin/gitvers-tool
echo "INSTALLATION COMPLETED ! ... [done]"

# test
sleep 1
gitvers-tool

# clear
rm -rf setup
